### ISSUE TITLE
How to populate "order price" dynamically

### ISSUE THREAD

**Issue by andrepferreira** [nileio/node-red-contrib-ccxt-v2#5] opened 2021-05-31 16:26 UTC
Not an issue, but a question.

I'm trying to populate the price field of the "createorder" API dynamically. The tip mentions that this can be done via a msg prop or flow, but I can't find how to reference the price value.

What's the best way to do this?  I am using the "limit" type and want to set the buy price dynamically based on some calcs in a proceeding function node.

Thanks

**Comment by nileio** [comment] 2021-06-01 02:39
@andrepferreira at the moment the fields cannot be passed in the msg if you are using Unified API. easy to change in future release.
however what you can do for now if you want to have dynamic values is use the Exchange API, then you can build any `Payload` you want and send it to the node. Payload field in the node config accepts dynamic values using `msg.` , so for example if you have a field name `myPayload` which includes all the parameters expected by the API, you can pass it to the node then from Payload field choose `msg.` then type the field name, that is `myPayload`
Make sure that you consult the exchange docs in order to know what is expected in the Payload, in some situations this is populated automatically for you but you should build the Payload per the exchange docs.

**Comment by andrepferreira** [comment] 2021-06-01 07:27
Hi there

Thanks for the reply, much appreciated. I have been trying the Exchange API, but could not get it to work. At this point I was just trying to use it to get the ticker for a pair (ETH/USD), but when I chose the API and populate the pair value I get the below error from the node:

"exchange[method] is not a function"

I am using Bitstamp exchange and have selected the /get_ticker/{pair}/ API and am using "ethusd" as the pair as per the API docs for Bitstamp. I have tried a few other API's too, but get similar errors. Pic of config below.

Am I doing something wrong here?

![image](https://user-images.githubusercontent.com/19912621/120283385-6ab74280-c2bb-11eb-8c20-16063cb04b49.png)

**Comment by nileio** [comment] 2021-06-02 10:05
@andrepferreira yeah I don't think this API will work, you picked an exchange that uses GET APIs include ***Path Parameters*** , the `Payload` field is used to send the data as a with the call `body`. This is typically the case with most exchanges. I am not sure how many other exchanges use Path Parameters. So this is a slightly new feature to substitue Path Parameters with actual values from the Payload field because it is not possible to determine whether the Payload is supposed to be sent with the call `body` or used to substitute Path Parameters with values which is surely required before executing the call for this type of call.
 
two options I can think of , 

1. I can make assumption that if the Parameter is in the path indicated always by the curly brackets, then it must be substituted with a value from the Payload, and then any other remaining keys that you may provide in the Payload will be sent as a POST with the call `body`. I think this might be a fair assumption.
2. just provide a way to dynamically provide values in the `msg` object for Unified APIs. but this yields those type of Exchange APIs unusable with this node.

Hope this makes sense. any thoughts?

**Comment by andrepferreira** [comment] 2021-06-02 14:17
Hi @nileio , ok, I see the issue.  I guess option 2 would be the easiest to implement, but not greatly desirable. Personally option 3 sounds the best long term solution and will help with other similar exchanges.

I'm not sure how option 2 would break the exchange "path" APIs though, but then I don't know the mechanics of the system that well. Is this a big deal?

**Comment by nileio** [comment] 2021-06-02 16:06
@andrepferreira I meant that option 2 does not really fix the `Path Parameters` issue .I think a new field to provide values for `Path Parameters` is needed. I i will get an update soon for this

**Comment by andrepferreira** [comment] 2021-06-02 16:09
Hi @nileio, that would be awesome, thanks!

**Comment by nileio** [comment] 2021-06-14 08:23
@andrepferreira sorry it took me a bit to look into this - was really flat out.
It turned out that original code actually handled path parameters out of the box !! it's been a while since I touched this code so I forgot that the expected behaviour is to provide the values to `Path Parameters` in the `Payload` field. 
In fact the editor already shows that by automatically populating the the expected `Path Parameters` when you select a method which includes `Path Parameters`. 
The issue turned out to be rather a small bug in handling the last character when there is only one path parameter !
anyway this is fixed now with  https://github.com/nileio/node-red-contrib-ccxt-v2/commit/bde387f7af5415fc8ba1adae29ca78be6af8fe95

Please test and report back

**Comment by andrepferreira** [comment] 2021-06-14 09:23
Hi @nileio, tested and it's all working!

Thanks very much!

**Closed** 2021-06-15 05:57 UTC
